version: '2'
services: 
#  database:
#    image: mongo:3
#    container_name: mtg_grimoire_database
  
  grimoire:
    image: java:8
    container_name: mtg_grimoire_app
#    links:
#      - database
    environment:
      DB_URL: "mongodb://test:test@database/mtg_grimoire"
      DB_NAME: "mtg_grimoire"
      PORT: "8080"
    ports:
      - 8080:8080
    volumes:
      - ./build/install/mtg-grimoire:/app
    working_dir: /app
    command: /app/bin/mtg-grimoire